### ISSUE TITLE
Unable to disable PasswordProtectedTransport

### ISSUE THREAD

**Issue by wifreema** [connectifier/jenkins-saml-plugin#2]
I was unable to attach questions to https://github.com/jenkinsci/saml-plugin.

jenkins-saml-plugin version: saml-0.2
We have a need to disable the passwordProtectedTransport and I do not see a way to do that in the xml config files.  

From Server side:
It looks like you are set up to use the PasswordProtectedTransport authentication method, which is native to the IdP. You are never getting redirected to Pubcookie.

**Comment by benmccann** [comment]
Hi, thank you for filing this issue. Apologies for closing this issue, but the right place to track is on https://issues.jenkins-ci.org with component "saml-plugin". We are removing the issue tracker from this repo to avoid further confusion. Please refile on the JIRA
