### ISSUE TITLE
No group collection for authorization plugins

### ISSUE THREAD

**Issue by jessejacob** [connectifier/jenkins-saml-plugin#3]
Issues aren't enabled on the other plugin repo, so I'm commenting here (also commented on the plugin page)

I'm a SAML newbie, but I got the plugin working for basic authentication with the ADFS IdP after finding the ADFS readme in the pac4j repo. I already had a comprehensive [matrix authorization strategy](https://wiki.jenkins-ci.org/display/JENKINS/Matrix+Authorization+Strategy+Plugin) based on Active Directory groups from the Active Directory plugin, but there isn't any [metadata file](http://en.wikipedia.org/wiki/SAML_2.0#Assertion_Consumer_Service_Metadata) with your plugin to designate a mapping strategy to request group/role memberships from the IdP. Looking at how straight-forward your actual plugin code is, it looks like you engineered it for a simple authentication only as you hardcode an empty array of authorities.

I would love to use this plugin, but I can't unless more work is done to implement granted authorities for the user based on group names coming back from the SAML response. Kohsuke wrote some great code for doing this using ADSI in the Active Directory plugin, I'm just light on exactly what I should ask my ADFS admin to provide and how to use pac4j to map it.

I would love to help, but I've already got my hands full with software projects and implementing Jenkins at my company. I'm primarily a .NET developer, so I'm not even sure how I would setup a Java dev environment on Windows to help out...I've helped several other plugin developers debug Windows-specific issues with their plugins in the past, but I've yet to roll up my sleeves and work on a plugin. After looking at your code and the AD plugin it looks like something I could tackle though. If you have some pointers for me to get setup and be able to build your plugin I would seriously consider forking the repo and submitting a pull request after I get it working, but I would probably need some help with the actual SAML part like the ACSM. If this is something you might be able to help with if I have questions, I would love to extend the plugin in the near future to support authorization.

**Comment by aRTURIUSS** [comment]
it would be very nice if you add groups support!

**Comment by antelmoa** [comment]
@benmccann I am also another person interested in this functionality.  I would also be willing to help you with this, but would like to get some help on how to get started and how to debug the code.  I am planning on doing the development on Red Hat, but could try your development environment if it is straight forward to setup(I have not done much JAVA development).  Thanks!

**Comment by rileyjenk** [comment]
@benmccann I am also very interested in this functionality. We would love to get off the AD plugin and move to SAML, however the fact that we can't use groups kills it for us.

**Comment by janfabry** [comment]
I think this has been implemented by now in jenkinsci/saml-plugin#2?

**Comment by cphillips-2u** [comment]
While I do believe this has been implemented, is there any documentation showing how it is supposed to work? I'm seemingly missing the puzzle piece that puts this and the Role-Based plugin together.

**Comment by janfabry** [comment]
@cphillips-2u I took some time today to update the documentation, expanding the info on groups and the Role Strategy Plugin. Currently the old version is still in the cache, you can view the new content here: https://wiki.jenkins-ci.org/pages/viewpage.action?pageId=73533028

@benmccann I think you can close this issue - or GitHub issues in general for this repository, as it's now managed by jenkinsci?

**Comment by cphillips-2u** [comment]
@janfabry thanks for fleshing out the documentation, this implementation isn't working for us it seems.  We use OneLogin, we are sending the groups, but jenkins doesn't seem to recognize them as groups, when using the Role Based Strategy plugin. 

Didn't know if someone maybe had proof of this actually working :) thanks!
