### ISSUE TITLE
Authorization related enhancements

### ISSUE THREAD

**Issue by pm-manoj-danane** [connectifier/jenkins-saml-plugin#5]
1. If we do not use "Overll All Read" permission authorization then a error page is shown in jenkins
2. If we use "Over All Read" permission SAML security is not enforced untill user tires to log in. This means general read features as availalbe to all public users.
3. To over come #1 we can use "Overl All Read" permission to "authenticated" users. 

There is not support for authenitcated authority in this plugin so if we use this in Matirx Based security; it doesnt work as user does not have authenticated authority.

**Comment by pm-manoj-danane** [comment]
I have done the changes related to this so that after successful login using SAML; user would get the "Authenticated" authority assinged which can be used in Authorization strategies.

I will send the pull request please review and merge the code so that it can be released.

**Comment by benmccann** [comment]
Hi, thank you for filing this issue. Apologies for closing this issue, but the right place to track is on https://issues.jenkins-ci.org with component "saml-plugin". We are removing the issue tracker from this repo to avoid further confusion. Please refile on the JIRA
