### ISSUE TITLE
Jenkins SAML with Auth0 integration

### ISSUE THREAD

**Issue by machzqcq** [connectifier/jenkins-saml-plugin#9]
# Auth0 Configuraiton
1. Created an app "Jenkins" 
2. Under Jenkins app > Settings, the field "Allowed Callback URLs = http://52.34.126.192:8080/securityRealm/finishLogin" (I am using AWS , so that ip might change)
3. Scroll down by clicking "Advanced Settings" . Under Endpoints > SAML, copied the URL "SAML metadata URL" and pasted in browser. It downloaded an XML file . We will use this later on jenkins side
4. Had an Auth0 user "abc@xyz.com" with connection "username-password-Authentication" database

I expect that after integration , I should be able to login to Jenkins with "abc@xyz.com"

# Jenkins Config
1. Installed SAML plugin -https://wiki.jenkins-ci.org/display/JENKINS/SAML+Plugin
2. Enabled global security , then SAML , pasted the above XML file (step 3 above) into field "IdP MetaData", selected "Role based strategy" radio and hit save

![image](https://cloud.githubusercontent.com/assets/6425159/11248882/79a4d2ee-8df1-11e5-9303-bcc9bd1151db.png)

3. No effect will be observed now as it is mentioned in SAML plugin that Anonymous has to be disabled before seeing changes. 
4. Go to Manage and Assign roles, and then uncheck any box for anonymous (since if Anonymous is enabled, then auth will be bypassed)
5. As soon as you hit save, you will be redirected to the Auth0 Login page (you can customize the login page on auth0, for now I went with defaults)
6. Now I login with the Auth0 user that I created in Auth0 config

I get the error as below

![image](https://cloud.githubusercontent.com/assets/6425159/11248957/fd762a14-8df1-11e5-8784-fc5bbfecdff8.png)

# LOGS
On the Auth0 side, the logs say that the user successfully logged in 

![image](https://cloud.githubusercontent.com/assets/6425159/11249010/5ab195d8-8df2-11e5-869f-d40f96c7fc6f.png)

Any help or thoughts are highly appreciated. Since Auth0 login says successful, I am posting this here, instead of Auth0 bugs

**Comment by madmuffin1** [comment]
I believe this repository is dead. The OP cross-posted this to http://stackoverflow.com/questions/33789104/jenkins-integration-with-auth0/36510013, I added a solution that worked for me over there.

**Comment by benmccann** [comment]
Hi, thank you for filing this issue. Apologies for closing this issue, but the right place to track is on https://issues.jenkins-ci.org with component "saml-plugin". We are removing the issue tracker from this repo to avoid further confusion. Please refile on the JIRA
